package com.healthcare.java.ai.langchain4j.tools;

import com.healthcare.java.ai.langchain4j.entity.Appointment;
import com.healthcare.java.ai.langchain4j.service.AppointmentService;
import dev.langchain4j.agent.tool.P;
import dev.langchain4j.agent.tool.Tool;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class AppointmentTools {

    @Autowired
    private AppointmentService appointmentService;


    @Tool(
            name = "Check Appointment Availability",
            value = "Check whether appointment slots are available based on department name, "
                    + "date, time period, and doctor name, and return the result to the user."
    )
    public boolean queryDepartment(
            @P(value = "Department Name") String name,
            @P(value = "Date") String date,
            @P(value = "Time (valid values: Morning, Afternoon)") String time,
            @P(value = "Doctor Name", required = false) String doctorName
    ) {

        System.out.println("Checking appointment availability");
        System.out.println("Department Name: " + name);
        System.out.println("Date: " + date);
        System.out.println("Time: " + time);
        System.out.println("Doctor Name: " + doctorName);

        // TODO Maintain doctor scheduling info:
        // If no doctor name is specified:
        //   Check whether any doctor is available under the given conditions
        //   (return true if available, otherwise false)

        // If a doctor name is specified:
        //   Check whether the doctor has a schedule (return false if none)
        //   If the doctor has a schedule, check whether the slot is fully booked
        //   (return false if full, true if available)

        return true;
    }

    @Tool(
        name = "Book Appointment",
        value = "Based on the given parameters, you MUST call the tool method queryDepartment first to check availability "
              + "and immediately reply to the user whether it is available. Then have the user confirm all "
              + "appointment details, and ONLY proceed with booking after confirmation. "
              + "If the user does not provide a specific doctor name, retrieve one from the vector database."
    )
    public String bookAppointment(Appointment appointment){

        // Check whether a matching appointment already exists in the database
        Appointment appointmentDB = appointmentService.getOne(appointment);

        if(appointmentDB == null){
            appointment.setId(null); // Prevent hallucinated ID values generated by the LLM

            if(appointmentService.save(appointment)){
                return "Appointment successfully booked. Returning appointment details.";
            } else {
                return "Appointment booking failed.";
            }
        }

        return "You already have an appointment at the same department and time.";
    }

    @Tool(
        name = "Cancel Appointment",
        value = "Based on the given parameters, check whether the appointment exists. "
              + "If it exists, delete the record and return a successful cancellation message. "
              + "Otherwise return a cancellation failure message."
    )
    public String cancelAppointment(Appointment appointment){

        Appointment appointmentDB = appointmentService.getOne(appointment);

        if(appointmentDB != null){
            // Delete appointment record
            if(appointmentService.removeById(appointmentDB.getId())){
                return "Appointment successfully cancelled.";
            } else {
                return "Appointment cancellation failed.";
            }
        }

        // Cancellation failed
        return "No appointment found. Please verify the department and appointment time.";
    }



}
